config/routes.rb
Rails.application.routes.draw do
  resources :recursousuarios
  resources :recursos
  resources :components
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recurso.rb
class Recurso < ApplicationRecord
end

app/models/recursousuario.rb
class Recursousuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recursos_controller.rb
class RecursosController < ApplicationController
  before_action :set_recurso, only: [:show, :edit, :update, :destroy]

  # GET /recursos
  # GET /recursos.json
  #busca la carpeta para traer todos de la base de datos
  def index
    @recursos = Recurso.all
  end

  # GET /recursos/1
  # GET /recursos/1.json
  #esto inicicializa los recursos
  def show
  end

  # GET /recursos/new
  #crea un nuevo recurso para almacenar datos
  def new
    @recurso = Recurso.new
  end

  # GET /recursos/1/edit
  ## aqui trae los datos para poder editar los datos
  def edit
  end

  # POST /recursos
  # POST /recursos.json
  #definimos un metodo que nos crea un recurso donde  nos recibe parametros  y guarada los datos
  def create
    @recurso = Recurso.new(recurso_params)

    respond_to do |format|
      if @recurso.save
        format.html { redirect_to @recurso, notice: 'Recurso was successfully created.' }
        format.json { render :show, status: :created, location: @recurso }
      else
        format.html { render :new }
        format.json { render json: @recurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recursos/1
  # PATCH/PUT /recursos/1.json
  #definimos un metdo donde   podemos  actualizar los datos de la base de datos
  def update
    respond_to do |format|
      if @recurso.update(recurso_params)
        format.html { redirect_to @recurso, notice: 'Recurso was successfully updated.' }
        format.json { render :show, status: :ok, location: @recurso }
      else
        format.html { render :edit }
        format.json { render json: @recurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recursos/1
  # DELETE /recursos/1.json
  # definimos un metodo para eliminar los datos  en la bd
  def destroy
    @recurso.destroy
    respond_to do |format|
      format.html { redirect_to recursos_url, notice: 'Recurso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

# definimos umetodo privado  para llamar y enviar datos  que recibe un parametro id
  private

    def set_recurso
      @recurso = Recurso.find(params[:id])
    end


    # definimos los parameros que recibimos  para poder realizar las acciones anteriores elimimar en listar datos  y guardar
    def recurso_params
      params.require(:recurso).permit(:id, :titulo, :nombre, :editorial)
    end
end

app/controllers/recursousuarios_controller.rb
class RecursousuariosController < ApplicationController
  before_action :set_recursousuario, only: [:show, :edit, :update, :destroy]

  # GET /recursousuarios
  # GET /recursousuarios.json
  def index
    @recursousuarios = Recursousuario.all
  end

  # GET /recursousuarios/1
  # GET /recursousuarios/1.json
  def show
  end

  # GET /recursousuarios/new
  def new
    @recursousuario = Recursousuario.new
  end

  # GET /recursousuarios/1/edit
  def edit
  end

  # POST /recursousuarios
  # POST /recursousuarios.json
  def create
    @recursousuario = Recursousuario.new(recursousuario_params)

    respond_to do |format|
      if @recursousuario.save
        format.html { redirect_to @recursousuario, notice: 'Recursousuario was successfully created.' }
        format.json { render :show, status: :created, location: @recursousuario }
      else
        format.html { render :new }
        format.json { render json: @recursousuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recursousuarios/1
  # PATCH/PUT /recursousuarios/1.json
  def update
    respond_to do |format|
      if @recursousuario.update(recursousuario_params)
        format.html { redirect_to @recursousuario, notice: 'Recursousuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @recursousuario }
      else
        format.html { render :edit }
        format.json { render json: @recursousuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recursousuarios/1
  # DELETE /recursousuarios/1.json
  def destroy
    @recursousuario.destroy
    respond_to do |format|
      format.html { redirect_to recursousuarios_url, notice: 'Recursousuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recursousuario
      @recursousuario = Recursousuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recursousuario_params
      params.require(:recursousuario).permit(:id, :email, :cedula, :libro, :idlibro)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recursos_helper.rb
module RecursosHelper
end

app/helpers/recursousuarios_helper.rb
module RecursousuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca</title>
    <%= csrf_meta_tags %>




    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/recursos/_form.html.erb
<%= form_with(model: recurso, local: true) do |form| %>
  <% if recurso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recurso.errors.count, "error") %> prohibited this recurso from being saved:</h2>

      <ul>
      <% recurso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id, id: :recurso_id %>
  </div>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :recurso_titulo %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :recurso_nombre %>
  </div>

  <div class="field">
    <%= form.label :editorial %>
    <%= form.text_field :editorial, id: :recurso_editorial %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recursos/edit.html.erb
<h1>Editar libro</h1>

<%= render 'form', recurso: @recurso %>

<%= link_to 'mostrar', @recurso %> |
<%= link_to 'atras', recursos_path %>

app/views/recursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>LIBRERIA</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Titulo</th>
      <th>Nombre</th>
      <th>Editorial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @recursos.each do |recurso| %>
      <tr>
        <td><%= recurso.id %></td>
        <td><%= recurso.titulo %></td>
        <td><%= recurso.nombre %></td>
        <td><%= recurso.editorial %></td>
        <td><%= link_to 'Mostrar', recurso %></td>
        <td><%= link_to 'Editar', edit_recurso_path(recurso) %></td>
        <td><%= link_to 'Eliminar', recurso, method: :delete, data: { confirm: 'desea eliminar datos?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= react_component 'recursos',{data: @recursos}%>
<br>

<%= link_to 'Agregar libro', new_recurso_path %>
<br>
<%= link_to 'Usuarios', recursousuarios_path %>

app/views/recursos/new.html.erb
<h1>Nuevo libro</h1>

<%= render 'form', recurso: @recurso %>

<%= link_to 'atras', recursos_path %>

app/views/recursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @recurso.id %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @recurso.titulo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @recurso.nombre %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @recurso.editorial %>
</p>

<%= link_to 'Editar', edit_recurso_path(@recurso) %> |
<%= link_to 'Atras', recursos_path %>

app/views/recursousuarios/_form.html.erb
<%= form_with(model: recursousuario, local: true) do |form| %>
  <% if recursousuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recursousuario.errors.count, "error") %> prohibited this recursousuario from being saved:</h2>

      <ul>
      <% recursousuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id, id: :recursousuario_id %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :recursousuario_email %>
  </div>

  <div class="field">
    <%= form.label :cedula %>
    <%= form.text_field :cedula, id: :recursousuario_cedula %>
  </div>

  <div class="field">
    <%= form.label :libro %>
    <%= form.text_field :libro, id: :recursousuario_libro %>
  </div>

  <div class="field">
    <%= form.label :idlibro %>
    <%= form.number_field :idlibro, id: :recursousuario_idlibro %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recursousuarios/edit.html.erb
<h1>Editing Recursousuario</h1>

<%= render 'form', recursousuario: @recursousuario %>

<%= link_to 'Mostrar', @recursousuario %> |
<%= link_to 'Atras', recursousuarios_path %>

app/views/recursousuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>USUARIOS</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th>Cedula</th>
      <th>Libro</th>
      <th>Idlibro</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @recursousuarios.each do |recursousuario| %>
      <tr>
        <td><%= recursousuario.id %></td>
        <td><%= recursousuario.email %></td>
        <td><%= recursousuario.cedula %></td>
        <td><%= recursousuario.libro %></td>
        <td><%= recursousuario.idlibro %></td>
        <td><%= link_to 'Mostrar', recursousuario %></td>
        <td><%= link_to 'Editar', edit_recursousuario_path(recursousuario) %></td>
        <td><%= link_to 'Eliminar', recursousuario, method: :delete, data: { confirm: 'desea eliminar datos?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= react_component 'recurso',{data: @recursousuarios}%>
<br>
<%= link_to 'Libreria', recursos_path %>
<br>
<%= link_to 'Nuevo Usuario', new_recursousuario_path %>

app/views/recursousuarios/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render 'form', recursousuario: @recursousuario %>

<%= link_to 'Atras', recursousuarios_path %>

app/views/recursousuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @recursousuario.id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @recursousuario.email %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @recursousuario.cedula %>
</p>

<p>
  <strong>Libro:</strong>
  <%= @recursousuario.libro %>
</p>

<p>
  <strong>Idlibro:</strong>
  <%= @recursousuario.idlibro %>
</p>

<%= link_to 'Editar', edit_recursousuario_path(@recursousuario) %> |
<%= link_to 'Atras', recursousuarios_path %>